#!/usr/bin/python

import sys
import helpers_nvidia 


targets = helpers_nvidia.list_targets()

config = (len(sys.argv) == 2 and sys.argv[1] == "config")

lines_status = []
lines_memory = []


for target in targets:
    
    target_info = helpers_nvidia.smi_info( target )


    basename = "nv%d"%target

    if config:
        lines_status.extend( [ 
                'graph_title nVidia card stats',
                'graph_category gpu',
                "%s_temp.label [%d]%s temp (C)"%(basename, target, target_info['name']),
                "%s_temp.type  GAUGE"%(basename),

                "%s_fan.label [%d]%s fan (%%)"%(basename, target, target_info['name']),
                "%s_fan.type  GAUGE"%(basename),
        ] )
    else:
        lines_status.extend( [
                "%s_temp.value %.1f"%(basename,target_info['temp']),
                "%s_fan.value %.1f"%(basename,target_info['fan_percent']),
                ])

    if config:
        lines_memory.extend( [
                'graph_title nVidia card memory use',
                'graph_category gpu',
                "%s_fbmem_u.label [%d]%s mem used"%(basename, target, target_info['name']),
                "%s_fbmem_u.type  GAUGE"%(basename),
                "%s_fbmem_u.draw AREA"%(basename),

                "%s_fbmem_f.label [%d]%s mem free"%(basename, target, target_info['name']),
                "%s_fbmem_f.type  GAUGE"%(basename),
                "%s_fbmem_f.draw STACK"%(basename),

                "%s_fbmem_t.label [%d]%s mem total"%(basename, target, target_info['name']),
                "%s_fbmem_t.type  GAUGE"%(basename),
                "%s_fbmem_t.draw LINE1"%(basename),
                ] )
    else:
        lines_memory.extend( [
                "%s_fbmem_u.value %d"%(basename, target_info['fbmem_used']),
                "%s_fbmem_f.value %d"%(basename, target_info['fbmem_free']),
                "%s_fbmem_t.value %d"%(basename, target_info['fbmem_total']),
                ] )


print 'multigraph nvidia_status'
print '\n'.join( lines_status )

print 'multigraph nvidia_memory'
print '\n'.join( lines_memory )
